PORT: "3000"
VPATH: "vls-123456"
VL_PORT: "8002"
MPATH: "vms-3456789"
VM_PORT: "8001"
XIEYI: "vms"
UUID: "3a8a1de5-7d41-45e2-88fe-0f538b822169"
CF_IP: "ip.sb"
SUB_NAME: "minecraft.com"
SUB_URL: ""
BAOHUO_URL: ""
NSERVER: "x'x:443"
NKEY: ""
NPORT: "443"
NTLS: "--tls"
TOK: ""
FILE_PATH: "/tmp"
